


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."copy_student_info_to_log"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  -- ดึงข้อมูลทุกอย่างที่จำเป็น (firstname, lastname, stu_id, class_id) มาในครั้งเดียว
  select stu_id, firstname, lastname, class_id 
  into new.stu_id_record, new.firstname_record, new.lastname_record, new.class_id_record
  from public.profiles
  where id = new.student_id;
  
  -- จัดการเรื่อง Note ว่าง (Default value)
  if (new.note is null or new.note = '') then
    new.note := '-';
  end if;
  
  return new;
end;
$$;


ALTER FUNCTION "public"."copy_student_info_to_log"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  insert into public.profiles (id, email, stu_id, firstname, lastname, class_id, role, created_at)
  values (
    new.id,
    new.email, -- ดึง email จาก auth.users มาใส่ตรงๆ
    coalesce(new.raw_user_meta_data->>'stu_id', '-'),
    coalesce(new.raw_user_meta_data->>'firstname', 'New'),
    coalesce(new.raw_user_meta_data->>'lastname', 'User'),
    coalesce(new.raw_user_meta_data->>'class_id', 'N/A'),
    coalesce(new.raw_user_meta_data->>'role', 'student'),
    new.created_at
  );
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."restrict_role_update"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
    begin
      -- ถ้ามีการพยายามเปลี่ยน role
      if old.role is distinct from new.role then
        -- ตรวจสอบว่าผู้ที่กำลังเปลี่ยน ใช่ admin หรือไม่
        if (auth.jwt() -> 'user_metadata' ->> 'role') is distinct from 'admin' then
          raise exception 'ไม่อนุญาตให้เปลี่ยนระดับสิทธิ์ (role) ด้วยตัวเอง';
        end if;
      end if;
      return new;
    end;
    $$;


ALTER FUNCTION "public"."restrict_role_update"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."sync_role_to_auth"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'auth', 'public'
    AS $$
begin
  -- อัปเดตข้อมูลในตาราง auth.users ช่อง raw_user_meta_data
  update auth.users
  set raw_user_meta_data = 
    coalesce(raw_user_meta_data, '{}'::jsonb) || jsonb_build_object('role', new.role)
  where id = new.id;
  
  return new;
end;
$$;


ALTER FUNCTION "public"."sync_role_to_auth"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."sync_user_email"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  update public.profiles
  set email = new.email
  where id = new.id;
  return new;
end;
$$;


ALTER FUNCTION "public"."sync_user_email"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."attendance_logs" (
    "id" bigint NOT NULL,
    "student_id" "uuid" NOT NULL,
    "status" "text" DEFAULT 'present'::"text" NOT NULL,
    "note" character varying(500) DEFAULT '-'::"text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "stu_id_record" character varying(20),
    "firstname_record" character varying(100),
    "lastname_record" character varying(100),
    "class_id_record" character varying(20),
    "subject" character varying(100) DEFAULT '-'::"text",
    "final_status" "text",
    "verification_status" "text" DEFAULT 'pending'::"text",
    "teacher_note" character varying(500),
    "verified_by" "uuid",
    "verified_at" timestamp with time zone,
    "attendance_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "leave_scope" "text" DEFAULT 'period'::"text",
    CONSTRAINT "check_leave_scope" CHECK (("leave_scope" = ANY (ARRAY['period'::"text", 'full_day'::"text", 'morning'::"text", 'afternoon'::"text"])))
);


ALTER TABLE "public"."attendance_logs" OWNER TO "postgres";


ALTER TABLE "public"."attendance_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."attendance_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "stu_id" character varying(20),
    "firstname" character varying(100),
    "lastname" character varying(100),
    "class_id" character varying,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "role" character varying DEFAULT 'student'::"text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    CONSTRAINT "check_role_types" CHECK ((("role")::"text" = ANY (ARRAY['admin'::"text", 'teacher'::"text", 'student'::"text", 'leader'::"text"])))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."schedule" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "subject_name" character varying(100) NOT NULL,
    "period" smallint,
    "room" character varying(50),
    "teacher_name" character varying(100),
    "day_of_week" smallint,
    "start_time" time without time zone NOT NULL,
    "end_time" time without time zone NOT NULL,
    "grade_level" character varying(20),
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "schedule_day_of_week_check" CHECK ((("day_of_week" >= 0) AND ("day_of_week" <= 6)))
);


ALTER TABLE "public"."schedule" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."school_activities" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" character varying(255) NOT NULL,
    "description" character varying(1000),
    "location" character varying(255),
    "activity_date" "date" NOT NULL,
    "start_time" time without time zone NOT NULL,
    "end_time" time without time zone NOT NULL,
    "organizer" character varying(100) DEFAULT 'โรงเรียน'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "check_times" CHECK (("start_time" < "end_time"))
);


ALTER TABLE "public"."school_activities" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_assets" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "asset_type" "text",
    "url" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "user_assets_asset_type_check" CHECK (("asset_type" = ANY (ARRAY['logo'::"text", 'banner'::"text", 'avatar'::"text"])))
);


ALTER TABLE "public"."user_assets" OWNER TO "postgres";


ALTER TABLE ONLY "public"."attendance_logs"
    ADD CONSTRAINT "attendance_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_stu_id_key" UNIQUE ("stu_id");



ALTER TABLE ONLY "public"."schedule"
    ADD CONSTRAINT "schedule_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."school_activities"
    ADD CONSTRAINT "school_activities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_assets"
    ADD CONSTRAINT "user_assets_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_attendance_logs_date" ON "public"."attendance_logs" USING "btree" ("attendance_date");



CREATE OR REPLACE TRIGGER "on_attendance_created" BEFORE INSERT ON "public"."attendance_logs" FOR EACH ROW EXECUTE FUNCTION "public"."copy_student_info_to_log"();



CREATE OR REPLACE TRIGGER "on_profile_role_update" AFTER INSERT OR UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."sync_role_to_auth"();



CREATE OR REPLACE TRIGGER "prevent_unauthorized_role_update" BEFORE UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."restrict_role_update"();



ALTER TABLE ONLY "public"."attendance_logs"
    ADD CONSTRAINT "attendance_logs_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."attendance_logs"
    ADD CONSTRAINT "attendance_logs_verified_by_fkey" FOREIGN KEY ("verified_by") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_assets"
    ADD CONSTRAINT "user_assets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



CREATE POLICY "Admins and Teachers can manage schedules" ON "public"."schedule" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND (("profiles"."role")::"text" = ANY (ARRAY['admin'::"text", 'teacher'::"text"]))))));



CREATE POLICY "Admins can manage all assets" ON "public"."user_assets" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND (("profiles"."role")::"text" = ANY (ARRAY['admin'::"text", 'teacher'::"text"]))))));



CREATE POLICY "Admins can manage user_assets" ON "public"."user_assets" TO "authenticated" USING (((("auth"."jwt"() -> 'user_metadata'::"text") ->> 'role'::"text") = 'admin'::"text"));



CREATE POLICY "Admins can update any profile" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (((("auth"."jwt"() -> 'user_metadata'::"text") ->> 'role'::"text") = 'admin'::"text"));



CREATE POLICY "Admins can view everything" ON "public"."profiles" FOR SELECT TO "authenticated" USING (((("auth"."jwt"() -> 'user_metadata'::"text") ->> 'role'::"text") = 'admin'::"text"));



CREATE POLICY "Admins, teachers, and leaders can view all attendance logs" ON "public"."attendance_logs" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND (("profiles"."role")::"text" = ANY (ARRAY['admin'::"text", 'teacher'::"text", 'leader'::"text"]))))));



CREATE POLICY "Anyone can view activities" ON "public"."school_activities" FOR SELECT USING (true);



CREATE POLICY "Anyone can view assets" ON "public"."user_assets" FOR SELECT USING (true);



CREATE POLICY "Public Access" ON "public"."schedule" FOR SELECT USING (true);



CREATE POLICY "Staff can manage activities" ON "public"."school_activities" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND (("profiles"."role")::"text" = ANY (ARRAY['admin'::"text", 'teacher'::"text"]))))));



CREATE POLICY "Staff update logs" ON "public"."attendance_logs" FOR UPDATE USING (((("auth"."jwt"() -> 'user_metadata'::"text") ->> 'role'::"text") = ANY (ARRAY['admin'::"text", 'teacher'::"text", 'leader'::"text"])));



CREATE POLICY "Students can insert their own logs" ON "public"."attendance_logs" FOR INSERT WITH CHECK ((("auth"."uid"() = "student_id") AND ("verification_status" = 'pending'::"text")));



CREATE POLICY "Students can view their own logs" ON "public"."attendance_logs" FOR SELECT USING (("auth"."uid"() = "student_id"));



CREATE POLICY "Teacher and Leader can view same class profiles" ON "public"."profiles" FOR SELECT TO "authenticated" USING ((((("auth"."jwt"() -> 'user_metadata'::"text") ->> 'role'::"text") = ANY (ARRAY['teacher'::"text", 'leader'::"text"])) AND ((("auth"."jwt"() -> 'user_metadata'::"text") ->> 'class_id'::"text") = ("class_id")::"text")));



CREATE POLICY "Users can manage their own assets" ON "public"."user_assets" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own profile" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));



CREATE POLICY "Users can view own profile" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



ALTER TABLE "public"."attendance_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."schedule" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."school_activities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_assets" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."copy_student_info_to_log"() TO "anon";
GRANT ALL ON FUNCTION "public"."copy_student_info_to_log"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."copy_student_info_to_log"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."restrict_role_update"() TO "anon";
GRANT ALL ON FUNCTION "public"."restrict_role_update"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."restrict_role_update"() TO "service_role";



GRANT ALL ON FUNCTION "public"."sync_role_to_auth"() TO "anon";
GRANT ALL ON FUNCTION "public"."sync_role_to_auth"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."sync_role_to_auth"() TO "service_role";



GRANT ALL ON FUNCTION "public"."sync_user_email"() TO "anon";
GRANT ALL ON FUNCTION "public"."sync_user_email"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."sync_user_email"() TO "service_role";


















GRANT ALL ON TABLE "public"."attendance_logs" TO "anon";
GRANT ALL ON TABLE "public"."attendance_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."attendance_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."attendance_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."attendance_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."attendance_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."schedule" TO "anon";
GRANT ALL ON TABLE "public"."schedule" TO "authenticated";
GRANT ALL ON TABLE "public"."schedule" TO "service_role";



GRANT ALL ON TABLE "public"."school_activities" TO "anon";
GRANT ALL ON TABLE "public"."school_activities" TO "authenticated";
GRANT ALL ON TABLE "public"."school_activities" TO "service_role";



GRANT ALL ON TABLE "public"."user_assets" TO "anon";
GRANT ALL ON TABLE "public"."user_assets" TO "authenticated";
GRANT ALL ON TABLE "public"."user_assets" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER on_auth_user_updated AFTER UPDATE OF email ON auth.users FOR EACH ROW EXECUTE FUNCTION public.sync_user_email();


  create policy "Admins can update any avatars"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'avatars'::text) AND (((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text)));



  create policy "Admins can upload any avatars"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'avatars'::text) AND (((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text)));



  create policy "Anyone can view avatars"
  on "storage"."objects"
  as permissive
  for select
  to public
using (true);



  create policy "Users can update own avatars"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])))
with check (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



  create policy "Users can upload own avatars"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



